from __future__ import annotations

from dataclasses import replace
from pathlib import Path

import pytest

from ragkit.adapters import (
    FilesystemSourceConnector,
    NoOpDocumentProjector,
    StructureAwareChunker,
    TextDocumentExtractor,
    TextFamilyClassifier,
)
from ragkit.domain import (
    IntegrityError,
    LimitExceededError,
    TextContent,
    TextSpanLocator,
    UnsupportedCapabilityError,
)
from ragkit.ports import (
    AcquiredAsset,
    ChunkingRequest,
    ExtractionRequest,
    ProjectionRequest,
    SourceRequest,
)

pytestmark = pytest.mark.unit


def _acquire(
    path: Path, *, max_assets: int = 20, max_bytes: int = 10_000
) -> tuple[AcquiredAsset, ...]:
    return FilesystemSourceConnector().fetch(
        SourceRequest(path.as_uri(), max_assets=max_assets, max_bytes_per_asset=max_bytes)
    )


def test_filesystem_connector_orders_directory_and_enforces_hard_limits(tmp_path: Path) -> None:
    (tmp_path / "z.txt").write_text("zeta")
    (tmp_path / "a.md").write_text("# Alpha")
    nested = tmp_path / "nested"
    nested.mkdir()
    (nested / "b.py").write_text("VALUE = 2")
    generated = tmp_path / "__pycache__"
    generated.mkdir()
    (generated / "ignored.py").write_text("do not index")

    first = _acquire(tmp_path)
    second = _acquire(tmp_path)
    assert first == second
    assert [Path(item.reference.uri or "").name for item in first] == ["a.md", "b.py", "z.txt"]
    assert all("__pycache__" not in (item.reference.uri or "") for item in first)
    assert all(
        item.reference.sha256 and item.reference.size_bytes == len(item.content) for item in first
    )

    with pytest.raises(LimitExceededError, match="asset count"):
        _acquire(tmp_path, max_assets=2)
    with pytest.raises(LimitExceededError, match="asset size"):
        _acquire(tmp_path / "a.md", max_bytes=2)
    with pytest.raises(UnsupportedCapabilityError, match="scheme"):
        FilesystemSourceConnector().fetch(SourceRequest("https://example.test/a", 1, 10))


def test_filesystem_connector_rejects_directory_symlinks_without_reading_target(
    tmp_path: Path,
) -> None:
    source = tmp_path / "source"
    source.mkdir()
    (source / "safe.txt").write_text("safe")
    outside = tmp_path / "outside-secret.txt"
    outside.write_text("must not be acquired")
    (source / "escape.txt").symlink_to(outside)

    with pytest.raises(IntegrityError, match="symbolic link"):
        _acquire(source)


def test_filesystem_connector_excludes_generated_python_bytecode(tmp_path: Path) -> None:
    (tmp_path / "source.py").write_text("VALUE = 1")
    cache = tmp_path / "__pycache__"
    cache.mkdir()
    (cache / "source.cpython-312.pyc").write_bytes(b"generated bytecode")

    assets = _acquire(tmp_path)

    assert [Path(item.reference.uri or "").name for item in assets] == ["source.py"]


@pytest.mark.parametrize(
    ("name", "content", "expected"),
    [
        ("note.txt", "plain text", "plain"),
        ("guide.md", "# Guide\n\nDetails", "markdown"),
        ("page.html", "<h1>Title</h1><p>Body</p>", "html"),
        ("mail.eml", "From: a@example.test\nSubject: Hi\n\nMessage body", "email"),
        ("tool.py", "def run():\n    return 1\n", "code"),
    ],
)
def test_text_families_extract_exact_source_spans(
    tmp_path: Path, name: str, content: str, expected: str
) -> None:
    path = tmp_path / name
    path.write_text(content)
    assets = _acquire(path)
    classifications = TextFamilyClassifier().classify(assets)
    documents = TextDocumentExtractor().extract(ExtractionRequest(assets, classifications, 1))

    assert len(documents) == 1
    assert documents[0].metadata["text_kind"] == expected
    assert documents[0].assets == (assets[0].reference,)
    decoded = assets[0].content.decode("utf-8")
    assert documents[0].parts
    for part in documents[0].parts:
        assert isinstance(part, TextContent)
        locator = part.provenance.locator
        assert isinstance(locator, TextSpanLocator)
        assert part.text == decoded[locator.start : locator.end]


def test_html_attribute_with_quoted_angle_bracket_keeps_markup_out_of_text(
    tmp_path: Path,
) -> None:
    path = tmp_path / "quoted.html"
    path.write_text('<div title="1 > 0">Visible</div>')
    assets = _acquire(path)
    classifications = TextFamilyClassifier().classify(assets)
    document = TextDocumentExtractor().extract(ExtractionRequest(assets, classifications, 1))[0]

    assert len(document.parts) == 1
    part = document.parts[0]
    assert isinstance(part, TextContent)
    assert part.text == "Visible"
    locator = part.provenance.locator
    assert isinstance(locator, TextSpanLocator)
    assert assets[0].content.decode()[locator.start : locator.end] == "Visible"


def test_classifier_and_extractor_reject_unsupported_corrupt_and_partial_input(
    tmp_path: Path,
) -> None:
    binary = tmp_path / "image.png"
    binary.write_bytes(b"not an image")
    assets = _acquire(binary)
    with pytest.raises(UnsupportedCapabilityError, match="media type"):
        TextFamilyClassifier().classify(assets)

    invalid = tmp_path / "broken.txt"
    invalid.write_bytes(b"\xff\xfe")
    assets = _acquire(invalid)
    classifications = TextFamilyClassifier().classify(assets)
    with pytest.raises(IntegrityError, match="UTF-8"):
        TextDocumentExtractor().extract(ExtractionRequest(assets, classifications, 1))

    empty_html = tmp_path / "empty.html"
    empty_html.write_text("<html><script>hidden()</script></html>")
    assets = _acquire(empty_html)
    classifications = TextFamilyClassifier().classify(assets)
    with pytest.raises(IntegrityError, match="searchable text"):
        TextDocumentExtractor().extract(ExtractionRequest(assets, classifications, 1))


def test_projector_never_silently_truncates_and_chunker_preserves_exact_spans(
    tmp_path: Path,
) -> None:
    source = tmp_path / "guide.md"
    source.write_text("# Heading\n\nFirst paragraph.\n\nSecond paragraph is longer.")
    assets = _acquire(source)
    classifications = TextFamilyClassifier().classify(assets)
    document = TextDocumentExtractor().extract(ExtractionRequest(assets, classifications, 1))[0]

    assert NoOpDocumentProjector().project(ProjectionRequest((document,), 10)) == (document,)
    second_part = replace(document.parts[0], part_id="text-copy")
    two_part_document = replace(document, parts=(document.parts[0], second_part))
    with pytest.raises(LimitExceededError, match="part limit"):
        NoOpDocumentProjector().project(ProjectionRequest((two_part_document,), 1))

    chunker = StructureAwareChunker(max_chars=18)
    chunks = chunker.chunk(ChunkingRequest((document,), 20))
    decoded = assets[0].content.decode()
    assert [item.ordinal for item in chunks] == list(range(len(chunks)))
    assert all(len(item.text) <= 18 for item in chunks)
    assert any(item.metadata["structural_path"] == "Heading" for item in chunks)
    for item in chunks:
        locator = item.provenance[0].locator
        assert isinstance(locator, TextSpanLocator)
        assert item.text == decoded[locator.start : locator.end]
    assert chunks == chunker.chunk(ChunkingRequest((document,), 20))
    with pytest.raises(LimitExceededError, match="chunk limit"):
        chunker.chunk(ChunkingRequest((document,), 1))

    alien = replace(document, parts=())
    assert chunker.chunk(ChunkingRequest((alien,), 2)) == ()
